import React from "react";

export default function Head() {
  return (
    <>
      <title>關於我們|ABOUT US</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
      <link rel="icon" href="/favicon.png" />
    </>
  );
}
